version: "3.8"

services:
  backend:
    build: ./backend-genshindle
    container_name: genshindle-backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    command: npm run start:prod

  frontend:
    build: ./genshindle
    container_name: genshindle-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run start
    depends_on:
      - backend
